### PR TITLE
Missing name setting in the subtheme .info file

### PR DESCRIPTION
**Pull request by fidelix**

### CODE REVIEW

**Comment by fidelix** [comment]
You're right. Changed it and also added a sample script using projectSlug (let me know if you want me to remove it)

**Comment by Snugug** [comment]
Not opposed to the sample script, but the script doesn't get generated, so that's going to error out in the browser. If it's going to be added, it needs to be created too.

**Comment by fidelix** [comment]
I know, but it is commented out, Sam. The user will probably know that he needs to create the JS file. I think...

**Comment by Snugug** [comment]
If it's going to be there, I'd like the file to exist. I didn't notice the comment on first glance, and users most likely wont notice it either and expect that file to exist.

**Comment by fidelix** [comment]
I'll do this in another issue later then. The fix for this 'name' problem needs to get in first because it crashes Drupal/Drush.

Thanks

**Pull request merged**
